### ISSUE TITLE
example-voting-app for Docker 1.12 Swarm Bundle?

### ISSUE THREAD

**Issue by veerendrav2** [docker/example-voting-app#34]
Hello,
I tried to use "Voting App" in docker 1.12 swarm (`Docker version 1.12.1, build 23cf638, experimental`), I followed here-->[https://blog.docker.com/2016/06/docker-app-bundle/](url) to how to use bundle. I was able to `docker deploy` the application and the containers are up and running. But, the ports were not exposed. I was not able to `curl http:127.0.0.1:5000` --> `curl: (7) Failed to connect to localhost port 5000: Connection refused`. Checked in `docker events`, the voting app container are continuously recreating!. (I have changed the yaml file: Removed "Build" and added "Image". Attaching the yaml file) 

My YAML File:

```
version: "2"

services:
  vote:
    image: docker/example-voting-app-vote
    command: python app.py
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"

  redis:
    image: redis:alpine
    ports: ["6379"]

  worker:
    image: docker/example-voting-app-worker

  db:
    image: postgres:9.4

  result:
    image: mantika/docker-example-voting-app-result
    command: nodemon --debug server.js
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
```
